### ISSUE TITLE
Multiple create credential with single aid issue in run-workflow.test.ts

### ISSUE THREAD

**Issue by HunnySajid** [GLEIF-IT/vlei-verifier-workflows#55]
In the `singlesig-single-user-light.yaml` file, multiple credentials with the same aid are not created. 
E.g 

```
ecr_cred1:
      id: 'ecr_cred1'
      type: 'issue_credential'
      attributes:
        personLegalName: 'Doula User'
        LEI: '875500ELOZEL05BVXV37'
      issuer_aid: 'le-aid-1'
      issuee_aid: 'ecr-aid-1'
      description: 'LE issues ECR vLEI credential (Birth Certified Doula)'
      credential: 'le_to_ecr_vlei_cred'
      credential_source: 'le_cred'
ecr_cred2:
      id: 'ecr_cred2'
      type: 'issue_credential'
      attributes:
        personLegalName: 'Doula User'
        LEI: '875500ELOZEL05BVXV37'
      issuer_aid: 'le-aid-1'
      issuee_aid: 'ecr-aid-1'
      description: 'LE issues ECR vLEI credential (Postpartum Certified Doula)'
      credential: 'le_to_ecr_vlei_cred2'
      credential_source: 'le_cred'
```

By looking at the logs, Lance suggest that, it seems like some filtering issue where the very first credential is being selected.

<img width="813" alt="Image" src="https://github.com/user-attachments/assets/41da9786-923a-4e86-97fe-33390955b414" />
